// Real people + connection data, generated by assets/build-connections-data.py
// from the attendance and registration files. Connection rule: same Zoom Room
// on the same Attendance Date. (Program totals sessions/hours are placeholders
// since the attendance sample covers a single day.)
const PEOPLE = window.LLT_PEOPLE || { learners: [], volunteers: [] };

function byId(list, id) {
  return list.find((p) => p.id === id);
}

function buildLearnerProfile(p) {
  return {
    ...p,
    role: "learner",
    title: "Certificate of Achievement",
    summary:
      "Your commitment helped build a welcoming space for practice, confidence, and connection.",
    certificate: `In recognition of completing ${p.sessions} English Conversation sessions, totaling ${p.hours} hours of participation during the 2025-2026 program year.`,
    certificateHtml: `In recognition of completing <span class="cert-stat">${escapeXml(p.sessions)}</span> English Conversation sessions, totaling <span class="cert-stat">${escapeXml(p.hours)}</span> hours of participation during the <span class="cert-year">2025-2026</span> program year.`,
  };
}

function buildVolunteerProfile(p) {
  return {
    ...p,
    role: "volunteer",
    title: "Certificate of Appreciation",
    summary:
      "Your service created space for learners to practice English, build confidence, and feel welcomed.",
    certificate: `In appreciation of ${p.sessions} volunteer conversation sessions, contributing ${p.hours} hours of service to support English learners during the 2025-2026 program year.`,
    certificateHtml: `In appreciation of <span class="cert-stat">${escapeXml(p.sessions)}</span> volunteer conversation sessions, contributing <span class="cert-stat">${escapeXml(p.hours)}</span> hours of service to support English learners during the <span class="cert-year">2025-2026</span> program year.`,
  };
}

// Resolve which person to show from ?id=<LLT_ID> or ?profile=learner|volunteer.
function pickProfile() {
  const params = new URLSearchParams(window.location.search);
  const id = params.get("id");
  if (id) {
    const l = byId(PEOPLE.learners, id);
    if (l) return buildLearnerProfile(l);
    const v = byId(PEOPLE.volunteers, id);
    if (v) return buildVolunteerProfile(v);
  }
  if (params.get("profile") === "volunteer" && PEOPLE.volunteers.length) {
    return buildVolunteerProfile(
      byId(PEOPLE.volunteers, PEOPLE.defaultVolunteerId) || PEOPLE.volunteers[0]
    );
  }
  return buildLearnerProfile(
    byId(PEOPLE.learners, PEOPLE.defaultLearnerId) || PEOPLE.learners[0]
  );
}

// Distinct connection places drive the third impact metric.
function connectionCount(profile) {
  return profile.role === "volunteer"
    ? (profile.partnerCountries || []).length
    : (profile.partnerCities || []).length;
}

const metrics = document.querySelectorAll(".metric strong");
const toast = document.querySelector("#toast");
const scrollCue = document.querySelector("#scroll-cue");
let currentProfile = null;

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function animateCount(element, value) {
  const duration = 850;
  const startedAt = performance.now();

  function tick(now) {
    const progress = Math.min((now - startedAt) / duration, 1);
    const eased = 1 - Math.pow(1 - progress, 3);
    element.textContent = Math.round(value * eased);

    if (progress < 1) {
      requestAnimationFrame(tick);
    }
  }

  requestAnimationFrame(tick);
}

function renderProfile(profile) {
  currentProfile = profile;

  document.querySelector("#person-name").textContent = profile.firstName;
  document.querySelector("#summary-text").textContent = profile.summary;
  document.querySelector("#certificate-name").textContent = profile.fullName;
  document.querySelector(".certificate-kicker").textContent = profile.title;
  document.querySelector("#certificate-body").innerHTML = profile.certificateHtml;

  const connectLabel = document.querySelector("#metric-connect-label");
  if (connectLabel) {
    connectLabel.textContent =
      profile.role === "volunteer" ? "Countries Connected" : "Cities Connected";
  }

  const values = [profile.sessions, profile.hours, connectionCount(profile)];
  metrics.forEach((metric, index) => animateCount(metric, values[index]));

  // Hand the active profile to the connection-map renderer (connections.js),
  // which may load after this script runs.
  window.LLT_ACTIVE_PROFILE = profile;
  document.dispatchEvent(new CustomEvent("llt:profile", { detail: profile }));
}

function showToast(message) {
  toast.textContent = message;
  toast.classList.add("show");
  window.setTimeout(() => toast.classList.remove("show"), 1700);
}

function fileBase(profile) {
  return `${profile.fullName.toLowerCase().replaceAll(" ", "-")}-llt-certificate`;
}

// PDF export: rasterize the actual on-page certificate (real logo, highlighter,
// gold title, italic year — exactly what's on screen) and drop it into a PDF
// page sized to the certificate.
document.querySelector("#download-pdf").addEventListener("click", async () => {
  const profile = currentProfile;
  const node = document.querySelector("#certificate");
  const jsPDF = window.jspdf && window.jspdf.jsPDF;

  if (typeof html2canvas !== "function" || !jsPDF) {
    showToast("PDF tools failed to load");
    return;
  }

  showToast("Building PDF…");
  try {
    if (document.fonts && document.fonts.ready) await document.fonts.ready;
    const scale = 3;
    const canvas = await html2canvas(node, {
      scale,
      backgroundColor: "#ffffff",
      useCORS: true,
    });
    const imgData = canvas.toDataURL("image/png");
    const w = canvas.width / scale;
    const h = canvas.height / scale;
    const pdf = new jsPDF({
      orientation: w > h ? "landscape" : "portrait",
      unit: "px",
      format: [w, h],
    });
    pdf.addImage(imgData, "PNG", 0, 0, w, h);
    pdf.save(`${fileBase(profile)}.pdf`);
    showToast("PDF downloaded");
  } catch (err) {
    console.error(err);
    showToast("Could not build PDF");
  }
});

function scrollToMore() {
  const target = document.querySelector("#impact-summary");
  const offset = target.getBoundingClientRect().top + window.scrollY - 24;
  window.scrollTo({ top: offset, behavior: "smooth" });
}

window.scrollToMore = scrollToMore;
scrollCue.addEventListener("click", scrollToMore);

function updateScrollCue() {
  scrollCue.classList.toggle("hidden", window.scrollY > 90);
}

window.addEventListener("scroll", updateScrollCue, { passive: true });
updateScrollCue();

renderProfile(pickProfile());
